import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { WhatsAppButton } from '@/components/WhatsAppButton';
import { HeroSection } from '@/components/HeroSection';
import { RepasseSection } from '@/components/RepasseSection';
import { PropertiesSection } from '@/components/PropertiesSection';
import { AboutSection } from '@/components/AboutSection';
import { Property } from '@/types/property';

const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Apartamento de Luxo no Altiplano',
    type: 'apartamento',
    purpose: 'repasse',
    neighborhood: 'Altiplano',
    address: 'Rua das Flores, 123',
    price: 650000,
    builtArea: 120,
    totalArea: 135,
    bedrooms: 3,
    bathrooms: 2,
    livingRooms: 2,
    parkingSpots: 2,
    hasPorter: true,
    hasSecurity: true,
    amenities: {
      piscina: true,
      academia: true,
      salaoFestas: true,
      churrasqueira: true,
      playground: true,
      saunas: false,
      quadraEsportiva: false,
      espacoGourmet: true,
      jardim: true,
      petPlace: false,
    },
    description: 'Excelente apartamento em localização privilegiada no Altiplano. Vista panorâmica, acabamento de primeira qualidade. Oportunidade única de repasse com condições especiais.',
    images: [],
    coverImage: '/placeholder.svg',
    featured: true,
    sold: false,
    order: 1,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Cobertura Duplex em Manaíra',
    type: 'cobertura',
    purpose: 'repasse',
    neighborhood: 'Manaíra',
    address: 'Av. Epitácio Pessoa, 500',
    price: 1200000,
    builtArea: 250,
    totalArea: 300,
    bedrooms: 4,
    bathrooms: 4,
    livingRooms: 3,
    parkingSpots: 3,
    hasPorter: true,
    hasSecurity: true,
    amenities: {
      piscina: true,
      academia: true,
      salaoFestas: true,
      churrasqueira: true,
      playground: true,
      saunas: true,
      quadraEsportiva: true,
      espacoGourmet: true,
      jardim: true,
      petPlace: true,
    },
    description: 'Cobertura duplex espetacular com vista para o mar. Piscina privativa, terraço gourmet. O melhor da vida está aqui.',
    images: [],
    coverImage: '/placeholder.svg',
    featured: true,
    sold: false,
    order: 2,
    createdAt: '2024-01-10',
    updatedAt: '2024-01-10',
  },
  {
    id: '3',
    title: 'Casa em Condomínio Portal do Sol',
    type: 'casa',
    purpose: 'repasse',
    neighborhood: 'Portal do Sol',
    address: 'Condomínio Vivendas do Sol',
    price: 890000,
    builtArea: 200,
    totalArea: 400,
    bedrooms: 4,
    bathrooms: 3,
    livingRooms: 2,
    parkingSpots: 4,
    hasPorter: true,
    hasSecurity: true,
    amenities: {
      piscina: true,
      academia: false,
      salaoFestas: true,
      churrasqueira: true,
      playground: true,
      saunas: false,
      quadraEsportiva: true,
      espacoGourmet: true,
      jardim: true,
      petPlace: true,
    },
    description: 'Casa ampla em condomínio fechado com segurança 24h. Área de lazer completa, muito verde e tranquilidade.',
    images: [],
    coverImage: '/placeholder.svg',
    featured: true,
    sold: false,
    order: 3,
    createdAt: '2024-01-08',
    updatedAt: '2024-01-08',
  },
  {
    id: '4',
    title: 'Apartamento Cabo Branco',
    type: 'apartamento',
    purpose: 'venda',
    neighborhood: 'Cabo Branco',
    address: 'Av. Cabo Branco, 200',
    price: 520000,
    builtArea: 95,
    totalArea: 105,
    bedrooms: 2,
    bathrooms: 2,
    livingRooms: 1,
    parkingSpots: 1,
    hasPorter: true,
    hasSecurity: true,
    amenities: {
      piscina: true,
      academia: true,
      salaoFestas: true,
      churrasqueira: false,
      playground: false,
      saunas: false,
      quadraEsportiva: false,
      espacoGourmet: false,
      jardim: true,
      petPlace: false,
    },
    description: 'Apartamento a 100m da praia de Cabo Branco. Vista para o mar, pronto para morar.',
    images: [],
    coverImage: '/placeholder.svg',
    featured: false,
    sold: false,
    order: 4,
    createdAt: '2024-01-05',
    updatedAt: '2024-01-05',
  },
  {
    id: '5',
    title: 'Flat em Tambaú',
    type: 'flat',
    purpose: 'aluguel',
    neighborhood: 'Tambaú',
    address: 'Av. Almirante Tamandaré, 80',
    price: 2800,
    builtArea: 45,
    totalArea: 50,
    bedrooms: 1,
    bathrooms: 1,
    livingRooms: 1,
    parkingSpots: 1,
    hasPorter: true,
    hasSecurity: true,
    amenities: {
      piscina: true,
      academia: true,
      salaoFestas: false,
      churrasqueira: false,
      playground: false,
      saunas: false,
      quadraEsportiva: false,
      espacoGourmet: false,
      jardim: false,
      petPlace: false,
    },
    description: 'Flat completo e mobiliado na orla de Tambaú. Ideal para investimento ou moradia.',
    images: [],
    coverImage: '/placeholder.svg',
    featured: false,
    sold: false,
    order: 5,
    createdAt: '2024-01-03',
    updatedAt: '2024-01-03',
  },
  {
    id: '6',
    title: 'Duplex no Bessa',
    type: 'duplex',
    purpose: 'repasse',
    neighborhood: 'Bessa',
    address: 'Rua Maria Rosa, 45',
    price: 780000,
    builtArea: 180,
    totalArea: 200,
    bedrooms: 3,
    bathrooms: 3,
    livingRooms: 2,
    parkingSpots: 2,
    hasPorter: true,
    hasSecurity: true,
    amenities: {
      piscina: true,
      academia: true,
      salaoFestas: true,
      churrasqueira: true,
      playground: true,
      saunas: false,
      quadraEsportiva: false,
      espacoGourmet: true,
      jardim: true,
      petPlace: true,
    },
    description: 'Duplex moderno no Bessa com acabamento premium. Excelente oportunidade de repasse.',
    images: [],
    coverImage: '/placeholder.svg',
    featured: true,
    sold: false,
    order: 6,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
];

const Index = () => {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <main>
        <HeroSection />
        <RepasseSection properties={mockProperties} />
        <PropertiesSection properties={mockProperties} />
        <AboutSection />
      </main>

      <Footer />
      <WhatsAppButton />
    </div>
  );
};

export default Index;
